CREATE TABLE `sucos`.`tbProdutos3` (
`PRODUTO` VARCHAR(20) NULL,
`NOME` VARCHAR(150) NULL,
`EMBALAGEM` VARCHAR(50) NULL,
`TAMANHO` VARCHAR(50) NULL,
`SABOR` VARCHAR(50) NULL,
`PRECO_LISTA` FLOAT NULL);